### ISSUE TITLE
Crashing with "unexpected character" on importing a png

### ISSUE THREAD

**Issue by tsheaff** [webpack-contrib/file-loader#271]
Here's my config

```
  const imageLoader = {
    test: /\.(jpg|jpeg|gif|png|svg)$/,
    loaders: ['file'],
    include: [path.resolve(__dirname, 'assets/source/images')],
  };
```

Then in the file:

```
import fooImage from '../assets/source/images/fooImage.png';
```

Then in React component's JSX `render`:
```
<img src={fooImage} />
```

Here's the runtime error:
```
SyntaxError: ~/assets/source/images/fooImage.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
  2 |
  3 |
  4 | IHDR
    at Parser.pp$5.raise (/Users/tsheaff/Code/private/calm/www/node_modules/babylon/lib/index.js:4454:13)
    at Parser.getTokenFromCode (/Users/tsheaff/Code/private/calm/www/node_modules/babylon/lib/index.js:1147:10)
    at Parser.readToken (/Users/tsheaff/Code/private/calm/www/node_modules/babylon/lib/index.js:776:19)
    at Parser.<anonymous> (/Users/tsheaff/Code/private/calm/www/node_modules/babylon/lib/index.js:7273:20)
    at Parser.readToken (/Users/tsheaff/Code/private/calm/www/node_modules/babylon/lib/index.js:6070:22)
    at Parser.nextToken (/Users/tsheaff/Code/private/calm/www/node_modules/babylon/lib/index.js:766:19)
    at Parser.parse (/Users/tsheaff/Code/private/calm/www/node_modules/babylon/lib/index.js:1672:10)
    at parse (/Users/tsheaff/Code/private/calm/www/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/Users/tsheaff/Code/private/calm/www/node_modules/babel-core/lib/transformation/file/index.js:517:15)
    at File.parseCode (/Users/tsheaff/Code/private/calm/www/node_modules/babel-core/lib/transformation/file/index.js:602:20)
    at /Users/tsheaff/Code/private/calm/www/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/Users/tsheaff/Code/private/calm/www/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/Users/tsheaff/Code/private/calm/www/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/Users/tsheaff/Code/private/calm/www/node_modules/babel-core/lib/api/node.js:152:10)
    at compile (/Users/tsheaff/Code/private/calm/www/node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/tsheaff/Code/private/calm/www/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tsheaff/Code/private/calm/www/node_modules/babel-register/lib/node.js:154:7)
```

**Comment by MyJanePress** [comment]
Where do I have to add in order to render images

**Comment by gtupak** [comment]
@tsheaff This might sound ignorant, but where is this "babel-register" file?

**Comment by Emobe** [comment]
@firegeek0218 @gtupak `require.extensions` has been deprecated by nodejs now

**Comment by puranis038** [comment]
Hi! I am facing the same issue now. Is there any solution for this? I have tried with file-loader, image-webpack-loader, etc but nothing is working for me. Please let me know. Thanks!

**Comment by evilebottnawi** [comment]
Something wrong in configuration

**Comment by puranis038** [comment]
I have imported .png file in react typescript. I am getting unexpected character while testing. I have tried installing image-webpack and other package but nothing is working for me. But is it a right way that I am doing? I can post my webpack.config.js file if needed.

**Comment by ovpv** [comment]
even I am facing this issue. 

I tried the following to fix:

- file-loader
- url-loader
- image-webpack

but it seems something is wrong with babel but cant figure out what as there is not proper error message:

`jpeg:1
����


SyntaxError: Invalid or unexpected token
    at compileFunction (<anonymous>)
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.newLoader [as .js] (/Users/ovpv/Documents/js/react/listr/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> `
