### ISSUE TITLE
Unable to install in windows...

### ISSUE THREAD

**Issue by tracker1** [webpack-contrib/file-loader#8]
There's an issue with the BigNum package, which requires OpenSSL header libraries for windows... honestly, is this _REALLY_ needed as a dependency?  Isn't there a JS based solution that can work for the needs of this module?

``` terminal
> node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bignum.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler
 used, but unwind semantics are not enabled. Specify /EHsc [D:\src\local\cc5-website\node_modules\file-loader\nod e_modules\bignum\build\bignum.vcxproj]
D:\src\local\cc5-website\node_modules\file-loader\node_modules\bignum\node_modules\nan\nan.h(1185): warning C4267 : '=' : conversion from 'size_t' to 'int', possible loss of data [D:\src\local\cc5-website\node_modules\file-load er\node_modules\bignum\build\bignum.vcxproj]
D:\src\local\cc5-website\node_modules\file-loader\node_modules\bignum\node_modules\nan\nan.h(1202): warning C4267 : '=' : conversion from 'size_t' to 'int', possible loss of data [D:\src\local\cc5-website\node_modules\file-load er\node_modules\bignum\build\bignum.vcxproj]
D:\src\local\cc5-website\node_modules\file-loader\node_modules\bignum\node_modules\nan\nan.h(1215): warning C4267 : 'initializing' : conversion from 'size_t' to 'int', possible loss of data [D:\src\local\cc5-website\node_module s\file-loader\node_modules\bignum\build\bignum.vcxproj]
D:\src\local\cc5-website\node_modules\file-loader\node_modules\bignum\node_modules\nan\nan.h(1229): warning C4267 : 'initializing' : conversion from 'size_t' to 'int', possible loss of data [D:\src\local\cc5-website\node_module s\file-loader\node_modules\bignum\build\bignum.vcxproj]
D:\src\local\cc5-website\node_modules\file-loader\node_modules\bignum\node_modules\nan\nan.h(1318): warning C4244 : 'return' : conversion from 'intptr_t' to 'int', possible loss of data [D:\src\local\cc5-website\node_modules\fi le-loader\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(9): fatal error C1083: Cannot open include file: 'openssl/bn.h': No such file or directory [D:\src\l ocal\cc5-website\node_modules\file-loader\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd D:\src\local\cc5-website\node_modules\file-loader\node_modules\bignum
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bignum@0.9.0
file-loader@0.7.2 node_modules\file-loader
```

**Comment by jhudson8** [comment]
any progress on this?  I'd love to remove bignum as a dependency as well
